"""Meaning of fields whose metadata label alone does not explain ownership or lifecycle."""
FIELD_NOTES={
'Lead.NTE_Applicant_Email_Status__c':'Applicant-side initial NTE receipt outcome. Applications deliberately have no applicant receipt here; EOI/guest use their route template. A later retry must preserve an accepted side.',
'Lead.NTE_Internal_Email_Status__c':'Independent outcome of the internal NTE intake notification to the configured routing user.',
'Lead.NTE_Email_Error__c':'Combined failed-side errors for initial NTE intake; it does not describe the separate supplementary or approval email path.',
'Lead.NTE_Application_Rejected__c':'Operator rejection removes an unconverted application from active panel/list review while retaining the Lead for history.',
'Lead.NTE_Interest_Not_Progressed__c':'Recorded rejection/not-progressed decision for an interest. Mutually exclusive with progressed; no Lead deletion occurs.',
'Lead.NTE_Interest_Progressed__c':'Interest has progressed after accepted application invitation. The retired manual progression action cannot substitute for a send.',
'Lead.NTE_Invitation_Status__c':'Mirrors the invitation dispatch lifecycle. Queued/Sent prevents stale rejection or another overlapping invitation request.',
'Lead.NTE_Invitation_Recipient__c':'Address recorded for the accepted invitation, preserving whom that progression reached.',
'Lead.NTE_Invitation_Sent_At__c':'Timestamp of Salesforce acceptance for the invitation; not an inbox-open or delivery receipt.',
'Lead.NTE_Update_Status__c':'Supplementary matching/application outcome. A matched or applied update is separate from its acknowledgement email outcome.',
'Lead.NTE_Update_Error__c':'Reason an update could not match/apply or an unexpected worker failed; retained for administrative recovery.',
'Lead.Volunteer_Applicant_Email_Status__c':'Volunteer applicant acknowledgement result, independent of the owner notification.',
'Lead.Volunteer_Internal_Email_Status__c':'Volunteer current-owner notification result; it does not use the NTE routing username.',
'Lead.Volunteer_Email_Error__c':'Per-Lead volunteer delivery errors; accepted sides survive retry of the other side.',
'Lead.Exhibitor_Interest_Areas__c':'Retained interest classification field. The current exhibitor-interest page uses the detailed interest/contribution questions instead; do not add this control solely because the field remains packaged.',
'Lead.Exhibitor_Space_Position__c':'Retained older space-position value for compatibility. Current pricing uses the single exact Exhibitor_Space_Selections__c choice.',
'Lead.Exhibitor_Space_Size__c':'Retained older space-size value for compatibility. Current pricing and staff allowance use the selected catalogue space.',
'Lead.Stand_Colleagues__c':'Retained older submitted staff-name field. Current supplementary forms use separate initial/top-up roster fields; the Opportunity consolidated roster remains operational.',
'Opportunity.NTE_Attendance_Status__c':'Manual attendance classification retained on the booking. It is not the Master Panel calculated Completed flag or a payment milestone.',
'Opportunity.NTE_Delivery_Window__c':'Delivery timing copied from Lead.Delivery_Window__c by an accepted Heavy Vehicle Details submission; later valid logistics submissions replace it.',
'NTE_Routing_Config__mdt.Application_Event_Code__c':'Exact edition required for final-pack eligibility. The API retains its earlier Application name; current invitation links are not gated by this value.',
'NTE_Routing_Config__mdt.Exhibitor_Application_URL__c':'HTTPS exhibitor application destination personalised into an invitation to an exhibitor expression of interest.',
'NTE_Routing_Config__mdt.Partner_Application_URL__c':'HTTPS partner/sponsor application destination personalised into an invitation to a partner/sponsor expression of interest.',
'NTE_Routing_Config__mdt.Exhibitor_Final_Pack_URL__c':'HTTPS final event information destination for eligible completed exhibitor bookings; blank makes that route ineligible.',
'NTE_Routing_Config__mdt.Partner_Final_Pack_URL__c':'HTTPS final event information destination for eligible completed partner/sponsor bookings; blank makes that route ineligible.',
'NTE_Stripe_Config__mdt.Allowed_Email__c':'Optional case-insensitive exact Primary Contact email filter. Blank permits any otherwise eligible recipient; a mismatch blocks payment preparation.',
'NTE_Stripe_Config__mdt.Enabled__c':'Activation switch for the Stripe booking coordinator. It is considered with payment method, positive booking value and optional reference prefix.',
'NTE_Stripe_Config__mdt.Expected_Account_Id__c':'Expected acct_ merchant identity. The Stripe client reads and verifies the actual account before creating or reusing payment resources.',
'NTE_Stripe_Config__mdt.Expected_Org_Id__c':'Exact 18-character destination Salesforce organisation ID; a different org cannot operate this saved configuration.',
'NTE_Stripe_Config__mdt.Live_Mode__c':'Selects the test or live named credential and required Stripe environment. Existing payment requests retain their original environment binding.',
'NTE_Stripe_Config__mdt.Reference_Prefix__c':'Optional case-sensitive booking-reference prefix used to select the enabled rollout scope. Blank imposes no prefix restriction.',
'NTE_Stripe_Config__mdt.Tax_Rate__c':'Percentage between 0 and 100 used to derive the saved gross fixed charge from net GBP pence; the rate is snapshotted on each payment request.',
'Opportunity.NTE_Approval_Email_Batch__c':'Random saved batch identity joining an exact set of pending conversion email requests and their queue/finalizer continuation.',
'Opportunity.NTE_Approval_Email_Error__c':'Last approval/provisional failure reason; correct that cause before using the booking retry action.',
'Opportunity.NTE_Approval_Email_Lead_Id__c':'Text identity of the exact converted source Lead. The approval service verifies the Lead-to-Opportunity association; this field is not a lookup relationship.',
'Opportunity.NTE_Approval_Email_Recipient__c':'Primary Contact address recorded for accepted provisional/complimentary delivery.',
'Opportunity.NTE_Approval_Email_Requested_At__c':'Time the conversion/retry saved a pending approval request, before background delivery.',
'Opportunity.NTE_Approval_Email_Requested_By__c':'Requesting user identity captured with the pending approval request.',
'Opportunity.NTE_Approval_Email_Sent_At__c':'Salesforce acceptance timestamp of the provisional/complimentary message.',
'Opportunity.NTE_Approval_Email_Status__c':'Pending, Sent or Failed approval email state; separate from paid confirmation dispatch and native Opportunity stage.',
'Opportunity.NTE_Final_Pack_Status__c':'Final-pack dispatch state. Completed bookings do not automatically set Sent; later preparation/finance changes preserve prior pack history.',
'Opportunity.NTE_Final_Pack_Recipient__c':'Address recorded for the accepted final event information email.',
'Opportunity.NTE_Final_Pack_Sent_At__c':'Acceptance timestamp of the final pack, retained when later top-up work reopens booking readiness.',
'Opportunity.NTE_Initial_Staff_Count__c':'Immutable initial purchased allocation copied from the conversion pricing result, including included and initially charged places.',
'Opportunity.NTE_Included_Staff_Count__c':'Catalogue allowance, two or four for the current exhibitor space. It is part of the initial count, not an additional allocation.',
'Opportunity.NTE_Total_Staff_Count__c':'Current roster total after accepted supplementary updates; includes any separately purchased exhibitor top-up.',
'Opportunity.NTE_Stand_Colleagues__c':'Current consolidated roster, one nonblank person per line. Exhibitor initial and top-up names are joined; partner updates replace the free roster.',
'Opportunity.NTE_Top_Up_Staff_Count__c':'Quantity of the first valid accepted exhibitor top-up purchase. Public later corrections cannot increase or decrease it.',
'Opportunity.NTE_Top_Up_Staff_Names__c':'Names for the accepted top-up quantity. Names can be corrected without changing the quantity or its paid/invoice history.',
'Opportunity.NTE_Top_Up_Staff_Unit_Price__c':'Saved net price per later staff place, currently GBP 50; not the initial additional-staff unit field.',
'Opportunity.NTE_Top_Up_Staff_Total__c':'Separate net top-up obligation. Its total including VAT is added to committed value; it never overwrites Opportunity.Amount or base payment.',
'Opportunity.NTE_Top_Up_Staff_Required__c':'Saved top-up answer. A later No cannot erase an already accepted positive top-up purchase.',
'Opportunity.NTE_Top_Up_Invoice_Required__c':'The separate staff charge requires an invoice/payment workflow; set on first valid positive top-up.',
'Opportunity.NTE_Top_Up_Invoice_Provided__c':'The separate staff invoice was provided. Does not mean the original booking invoice was provided.',
'Opportunity.NTE_Top_Up_Payment_Received__c':'Manual receipt of the separate staff payment. Does not send another initial-booking confirmation.',
'NTE_Email_Dispatch__c.Contact__c':'Optional snapshot association to the booking Primary Contact selected for this email. The email address and fingerprint are saved separately.',
'NTE_Email_Dispatch__c.Dispatch_Key__c':'Unique external SHA256 identity of kind, run and target. Repeated queue/retry uses the same row rather than generating another send.',
'NTE_Email_Dispatch__c.Error__c':'Specific preparation, changed-snapshot, queue or send failure retained for retry review.',
'NTE_Email_Dispatch__c.Event_Code__c':'Edition captured for the reviewed message, checked against current eligibility before delivery.',
'NTE_Email_Dispatch__c.Fingerprint__c':'Hash of recipient and merged booking/route facts. A change after review prevents sending stale content.',
'NTE_Email_Dispatch__c.Kind__c':'One implemented invitation, staff/vehicle/logo reminder, final-pack or booking-payment-confirmation route.',
'NTE_Email_Dispatch__c.Lead__c':'Optional source interest Lead for invitations; mutually contextual with the booking target in application logic.',
'NTE_Email_Dispatch__c.Link__c':'Saved participant-specific application/update/final-pack HTTPS action destination.',
'NTE_Email_Dispatch__c.Message__c':'Saved reviewed plain-text message content, including its supported personalisation tokens; HTML is rendered by the service.',
'NTE_Email_Dispatch__c.Opportunity__c':'Optional booking target for preparation, pack or paid-confirmation messages.',
'NTE_Email_Dispatch__c.Recipient__c':'The saved email address being reviewed/sent; arbitrary fallback contact addresses are not used.',
'NTE_Email_Dispatch__c.Run_Id__c':'One composer run identity; independent reminder runs can occur while preparation remains outstanding. Payment confirmation has a fixed run identity.',
'NTE_Email_Dispatch__c.Sent_At__c':'Time Salesforce accepted this individual message, not final recipient inbox delivery.',
'NTE_Email_Dispatch__c.Status__c':'Queued, Sent, Failed or Skipped request outcome. Only supported failed rows are retryable.',
'NTE_Email_Dispatch__c.Subject__c':'Saved reviewed subject, revalidated after personalisation for length and content.',
'NTE_Payment_Request__c.Amount_Minor__c':'Fixed gross charge including saved VAT, in integer GBP pence. This is the Stripe Price amount.',
'NTE_Payment_Request__c.Batch_Key__c':'Approval batch that should resume after this request completes or fails.',
'NTE_Payment_Request__c.Charge_Key__c':'Unique external org ID plus Opportunity ID plus Booking identity. Also anchors the stable Price/Link idempotency keys.',
'NTE_Payment_Request__c.Currency__c':'Saved Stripe currency code; this implementation requires gbp.',
'NTE_Payment_Request__c.Delivered_At__c':'Acceptance time of the provisional email containing this verified link, not payment collection time.',
'NTE_Payment_Request__c.Description__c':'Year-neutral NTE booking description containing the booking reference; used as the new Stripe Product name.',
'NTE_Payment_Request__c.Error__c':'Last preparation/reverification or ambiguous external outcome requiring repair or manual review.',
'NTE_Payment_Request__c.First_Attempt_At__c':'First external creation attempt. An ambiguous request older than 23 hours is held for review.',
'NTE_Payment_Request__c.Kind__c':'Charge kind. The active coordinator creates Booking requests; low-level staff top-up support is not automatic orchestration.',
'NTE_Payment_Request__c.Link_Id__c':'Persisted Stripe Payment Link identity used for verification and safe reuse on email retry.',
'NTE_Payment_Request__c.Live_Mode__c':'Saved environment binding. A test request cannot be reused after switching configuration to live.',
'NTE_Payment_Request__c.Net_Minor__c':'Saved initial net booking amount in pence, excluding VAT and later separate top-ups.',
'NTE_Payment_Request__c.Opportunity__c':'Booking lookup for this charge. Custom lookup deletion is SetNull; the remaining snapshot preserves request evidence.',
'NTE_Payment_Request__c.Payment_URL__c':'Verified buy.stripe.com URL inserted into the Pay Now button after all readiness checks.',
'NTE_Payment_Request__c.Price_Id__c':'Persisted fixed Stripe Price identity; retained if link creation fails so retry can reuse it.',
'NTE_Payment_Request__c.Recipient__c':'Exact saved Primary Contact address bound to the charge/email snapshot.',
'NTE_Payment_Request__c.Reference__c':'Saved booking reference copied into Stripe resource metadata and the recipient message.',
'NTE_Payment_Request__c.Source_Fingerprint__c':'Hash of source identity, components, recipient and payment configuration. Changes prevent reusing an old issued proposal.',
'NTE_Payment_Request__c.Source_Lead_Id__c':'Text ID of the converted application source, validated by the coordinator; not a metadata lookup.',
'NTE_Payment_Request__c.Status__c':'External request preparation status. Ready means recently verified and usable for email, not paid.',
'NTE_Payment_Request__c.Stripe_Account__c':'Saved expected acct_ merchant identity verified before resource creation.',
'NTE_Payment_Request__c.Tax_Rate__c':'Saved percentage used to calculate the gross fixed request. The client confirmed 20% VAT on 13 September; preserve the rate saved on the request.',
'NTE_Payment_Request__c.Verified_At__c':'Time the resource contract was checked; email requires a matching recent verification within five minutes.',
}
def note_for(obj,api):
    if obj+'.'+api in FIELD_NOTES:return FIELD_NOTES[obj+'.'+api]
    if obj in ['Account','Contact']:
        notes={
            'NTE_Booking_Reference__c':'Latest classified application booking reference copied during conversion; a text summary, not the relationship to that booking.',
            'NTE_Event_Code__c':'Latest classified application edition copied during conversion; earlier event history remains on related Opportunities.',
            'NTE_Last_Application_Date__c':'Conversion Flow execution timestamp from $Flow.CurrentDateTime; later conversions replace this latest-application summary.',
            'NTE_Source_Form_Type__c':'Latest converted commercial application type copied from Lead.Web_Form_Type__c.',
            'NTE_Contact_Role__c':'Classification text set to Applicant / event contact during conversion. The independent OpportunityContactRole record controls the booking Primary Contact.'}
        if api in notes:return notes[api]
    if obj=='Opportunity':
        if api.startswith('NTE_Last_Update_'):return 'Audit of the last accepted supplementary update: its form/type, declaration, processing time or error. Distinct from the original application declaration and separate receipt outcome.'
        if api.startswith(('NTE_Heavy_Item_','NTE_Haulier_')):return 'Saved logistics replacement supplied by a valid Heavy Vehicle Details submission. Optional item groups must be complete if started; omitted optional groups clear their prior values.'
        if api.startswith(('NTE_Top_Up_Invoice_','NTE_Top_Up_Payment_'))and api.endswith(('_At__c','_By__c')):return 'Timestamp or actor for the separate staff top-up milestone. Initial booking finance stamps are preserved.'
        if api.startswith(('NTE_Quote_Provided_','NTE_Invoice_Provided_','NTE_Payment_Received_','NTE_Payment_Recorded_')):return 'Initial booking milestone evidence stamped by the validated finance action; names/times are preserved on rejected repeated actions.'
        if api.startswith('NTE_Event_Contact_') or api.startswith('NTE_Secondary_Contact_'):return 'Descriptive event-day or secondary contact detail from the application/logistics submission. It is not an email-recipient fallback for a missing Primary Contact.'
        if api.startswith(('NTE_Invoiced_','NTE_Invoice_Contact_','NTE_Invoice_Address','NTE_Invoice_Additional','NTE_Purchase_Order','NTE_Trading_Name','NTE_Supplier_Agreement')):return 'Saved billing/procurement detail for the manual finance process and reports. Collecting it does not create a Salesforce or Stripe invoice.'
    return ''
