"""Component-specific contracts, read against all four current JavaScript bundles."""
HOME = {
    'connectedCallback': 'Registers window-focus and document-visibility listeners and loads the event portfolio.',
    'disconnectedCallback': 'Removes both listeners, clears the refresh timer and increments requestSequence to discard any response arriving after removal.',
    'handleWindowFocus': 'Schedules a refresh when the window regains focus.',
    'handleVisibilityChange': 'Schedules a refresh only when document.visibilityState becomes visible.',
    'scheduleLiveRefresh': 'Replaces any pending refresh with a 150 ms timer, then calls loadDashboard.',
    'controlsDisabled': 'Disables the event selector and refresh control while loading or when eventOptions is empty.',
    'showInitialLoading': 'Shows the initial loading state only while loading and before a dashboard has been accepted.',
    'handleEventChange': 'Ignores an unchanged edition; otherwise stores event.detail.value, clears hasDashboard and loads the selected edition.',
    'handleRefresh': 'Reloads the currently selected event portfolio.',
    'loadDashboard': 'Calls getHomeDashboard with the selected edition or null. A monotonically increasing requestSequence discards superseded responses; the latest response is parsed and applied, or the portfolio error state is shown.',
    'applyDashboard': 'Loads event choices, returned edition, refresh time, headlines, pipeline, finance readiness and booking mix. Adds an unlisted returned edition to the selector and shows a pricing-check note only when pricingReviewCount is positive.',
    'parseResponse': 'Accepts an object directly, substitutes {} for a missing response, or JSON-parses a string. Invalid JSON throws the dashboard-response error.',
    'normalizeEventOptions': 'Accepts an array of strings or objects. Object value precedence is value, code, eventCode; label precedence is label, name, value. Entries without a value are removed.',
    'normalizeHeadline': 'Produces Applications, Approved applications, Invoiced, Still to collect and Paid in that order. Resolves configured aliases from an array or object, formats each value and record count, and highlights Approved applications.',
    'normalizePipeline': 'Accepts stage rows or a keyed object. Resolves exhibitor, partner and total amounts; a missing/zero total falls back to exhibitor plus partner. Each audience bar is scaled against that audience’s largest stage. Share uses the supplied nonzero percentage or total divided by the largest stage total; these overlapping stages are not an additive funnel.',
    'normalizeReadiness': 'Accepts an array or the configured quote/invoice/payment/paid object aliases. Each segment uses its supplied nonzero percentage or its value divided by the sum of the displayed readiness values, then formats the amount and width.',
    'normalizeReadinessItem': 'Resolves label/name, a normalised key, metricValue and percentage/share/progress; missing labels become Status plus a one-based index.',
    'normalizeBookingMix': 'Resolves exhibitor/exhibitors and partnerSponsor/partner/sponsors groups, totals their records and values, then presents each group’s contribution.',
    'bookingGroup': 'Reads the group record count and value. Average uses averageValue/average/avgValue when nonzero, otherwise value divided by records, or zero for an empty group.',
    'presentBookingGroup': 'Formats record count and value with rounded percentages of the combined groups, and formats average booking value. A zero denominator yields 0%.',
    'emptyBookingMix': 'Initialises both participant groups to 0 records, £0 value and £0 average while no portfolio is available.',
    'firstObject': 'Returns the first alias whose value is neither null nor undefined. Objects pass through; scalar values become { value }; no match returns {}.',
    'metricValue': 'Uses the first non-null value among value, amount, totalValue and total, converted through toNumber.',
    'metricRecords': 'Uses the first non-null value among records, recordCount and count, converted through toNumber.',
    'toNumber': 'Preserves finite numbers. For strings, removes all characters except digits, decimal point and minus sign before Number conversion. Missing, non-string and non-finite values become zero.',
    'toKey': 'Converts camel case and non-alphanumeric separators to lowercase hyphenated keys; an empty result becomes item-<index>.',
    'widthStyle': 'Clamps the numeric percentage to 0–100 and returns a CSS width with two decimal places.',
    'formatCurrency': 'Formats the normalised number as GBP using en-GB with zero decimal places for portfolio headlines and charts.',
    'formatDateTime': 'Formats a valid Date or date value using en-GB day, abbreviated month, year and 24-hour time in the browser timezone. Invalid dates display an em dash.'
}
PANEL = {
    'connectedCallback': 'Registers focus/visibility listeners and loads the initial INTEREST view with All time, all owners and 25 rows per page.',
    'disconnectedCallback': 'Removes listeners; clears refresh, conversion-monitor and preview timers; invalidates dashboard/communication/preview sequences; and clears active communication state.',
    'renderedCallback': 'When modalNeedsFocus is set, focuses the dialog’s data-modal-focus control once and clears the flag.',
    'handleWindowFocus': 'Schedules a refresh after Salesforce regains focus, including a return from the separate conversion tab.',
    'handleVisibilityChange': 'Schedules a refresh when the document becomes visible.',
    'scheduleLiveRefresh': 'Debounces refresh by 150 ms while preserving row selection. Both scheduling and execution are suppressed during a record action, open communication dialog or communication preparation/send.',
    'eventOptions': 'Returns response.eventOptions or an empty selector list.',
    'ownerOptions': 'Returns response.ownerOptions; its fallback is one All owners choice with an empty value.',
    'guestBreakdown': 'Presents overview key guests as pending versus captured.',
    'interestBreakdown': 'Presents overview key interest as open versus decided.',
    'applicationBreakdown': 'Presents overview key applications as awaiting review versus approved.',
    'bookingBreakdown': 'Presents overview key approved as still in progress versus fully complete. Completion is rounded completed/total × 100, or zero when empty; the donut angle is that percentage × 3.6 degrees.',
    'quoteBreakdown': 'Presents overview key quotes as outstanding versus provided.',
    'invoiceBreakdown': 'Presents overview key invoices as outstanding versus provided.',
    'paymentBreakdown': 'Presents overview key payments as outstanding versus received.',
    'logisticsBreakdown': 'Presents overview key heavy as outstanding versus completed.',
    'staffBreakdown': 'Presents overview key staff as outstanding versus completed.',
    'logoBreakdown': 'Presents overview key logos as outstanding versus completed.',
    'buildBreakdownMetric': 'Finds the requested response.overview key, converts missing totals/counts to zero, clamps each progress width to 0–100%, and creates the accessible total/in-progress/completed description.',
    'pipeline': 'Decorates response.pipeline with the active-stage class and aria-pressed value. The Completed tile appends the summary complete percentage, defaulting to 0%.',
    'activeStage': 'Finds the STAGE_CONFIGURATION group containing viewKey; views outside the configured groups fall back to interest for path highlighting.',
    'stageOptions': 'Maps the active stage’s configured refinement keys to response.workQueues and marks the selected option. A missing queue receives its key as label, count zero and the standard record icon.',
    'hasStageOptions': 'Shows refinement controls when stageOptions contains at least one item.',
    'selectedQueue': 'Uses response.selectedView for the record-list heading; fallback is NTE records with the selected-filter description.',
    'isGuestView': 'True only for GUESTS.',
    'isInterestView': 'True for INTEREST, INTEREST_EXHIBITOR or INTEREST_PARTNER.',
    'isApplicationView': 'True for APPLICATION_REVIEW, APPLICATION_EXHIBITOR or APPLICATION_PARTNER.',
    'isFinanceView': 'True for FINANCE_DUE, QUOTE_REQUIRED, INVOICE_REQUIRED, PAYMENT_DUE or PAYMENT_COMPLETE.',
    'financeAmountLabel': 'Labels finance values Amount (inc VAT), including the actionable booking or top-up charge according to the current queue.',
    'hasRowActions': 'Shows the action column if any row has an interest/application decision or any visible base/top-up quote, invoice or payment milestone action.',
    'isApprovedView': 'True for APPROVED, APPROVED_EXHIBITOR or APPROVED_PARTNER.',
    'isCompletedView': 'True for COMPLETED, FINAL_PACK_DUE or FINAL_PACK_SENT.',
    'isHeavyView': 'True only for HEAVY_DUE.',
    'isStaffView': 'True only for STAFF_DUE.',
    'isLogoView': 'True only for LOGO_DUE.',
    'isUpdatesView': 'True only for the combined READINESS_DUE view.',
    'isRecentView': 'True only for RECENT.',
    'actionColumnLabel': 'Uses Decision in interest views and Action elsewhere.',
    'canRemindAll': 'Shows the bulk reminder entry point only in HEAVY_DUE, STAFF_DUE or LOGO_DUE.',
    'canDistributeFinalPack': 'Shows final-pack distribution in COMPLETED and FINAL_PACK_DUE, excluding FINAL_PACK_SENT.',
    'communicationBusy': 'True during draft preparation or email queuing.',
    'panelControlsDisabled': 'Locks panel actions/filters during loading, a record action, communication preparation/queuing or any open communication dialog.',
    'visibleRows': 'Adds the current panel lock to every row action. Invitation actions also keep their own Queued/Sent lock.',
    'visibleCommunicationRecipients': 'Disables recipient selection while communication is busy or the server has marked that recipient ineligible.',
    'selectedEmailRecipients': 'Includes only recipients whose selected and eligible flags are both true.',
    'selectedEmailRecipientCount': 'Counts the eligible selected recipients used in the send request.',
    'availableRecipientCount': 'Counts every eligible draft recipient, whether selected or not.',
    'sendCommunicationDisabled': 'Blocks Send while busy, with a stale draft, when draft.canSend is false, with no selected recipient or more than recipientLimit (default 500), with blank trimmed subject/body, or until a current preview is ready and no preview is loading.',
    'sendCommunicationLabel': 'Displays Queuing emails… during the send request; otherwise Send to <selected count>.',
    'recipientOptions': 'Builds the preview selector from eligible selected recipients. Labels combine distinct nonempty company/name values; the option value is the source record ID.',
    'hasSelectedEmailRecipients': 'Shows recipient-dependent preview controls when the selected eligible count is positive.',
    'tableClass': 'Converts the view key to lowercase with hyphens to select the corresponding data-table CSS layout.',
    'selectedRecord': 'Finds selectedRecordId among the current page’s rows for the detail sidebar.',
    'hasRows': 'True when the current page contains at least one row.',
    'hasPrevious': 'True when offsetRows is greater than zero.',
    'hasNext': 'Prefers the server’s hasNextPage flag; if absent, checks offsetRows + 25 against totalRows.',
    'previousDisabled': 'Disables Previous when the panel is locked or there is no earlier page.',
    'nextDisabled': 'Disables Next when the panel is locked or there is no later page.',
    'pageLabel': 'Displays the one-based visible range and total, or 0 records. If rowsLimited is true, appends the server’s accessibleRows as the latest records available.',
    'loadDashboard': 'Calls getDashboard with edition, time range, owner/null, view key, page size 25 and offset. Ignores superseded responses, adopts returned scope/pagination and decorates rows. Preserves the selected record if still on the page, otherwise selects the first row. Communication work prevents loading.',
    'decorateRow': 'Combines server canMark flags with the current finance refinement to expose only relevant base/top-up actions. Derives Lead/Opportunity, guest/interest/application flags, contact links and detail fallbacks. Queued/Sent invitations disable their action; Opportunity details use Primary contact and optional event-day contact.',
    'financeStatusForView': 'Check pricing takes priority. Quote view says Quote required; invoice/payment views choose the base booking while its corresponding obligation remains outstanding, then the staff top-up. Paid view says Payment confirmed; combined view keeps the server label.',
    'financeAmountForView': 'Quote view uses baseAmount. Invoice/payment refinements use baseAmount while the base obligation is outstanding, then topUpAmount. Combined finance prioritises base quote/invoice, top-up invoice, base payment, then top-up payment. Otherwise returns the combined row.amount.',
    'decorateRows': 'Updates each row’s selected CSS class and accessible selection label after a sidebar selection change.',
    'leadConversionPageReference': 'Builds a standard__component reference to runtime_sales_lead__convertDesktopConsole, with the exact Lead ID in leadConvert__leadId.',
    'statusClass': 'Marks complete/provided/paid/payment confirmed/not required/not applicable as complete. Check pricing or text containing required/due/confirmed is due; remaining statuses are neutral.',
    'emailStatusClass': 'Maps Sent to complete, Failed to failed, Pending/Queued to due, and other or missing email states to neutral.',
    'handleEventChange': 'Stores the edition selector value and resets to the first page without preserving row selection; ignored while the panel is locked.',
    'handleTimeChange': 'Stores the All time/Today/7/30/90-day selector value and reloads from the first page; ignored while locked.',
    'handleOwnerChange': 'Stores the owner selector value and reloads from the first page; ignored while locked.',
    'handleStageOptionSelect': 'Uses the clicked refinement’s data-view as viewKey and reloads from page one.',
    'handlePipelineSelect': 'Uses the clicked stage’s configured combinedView, falling back to its data-view, then reloads from page one.',
    'handleOverviewSelect': 'Uses the clicked overview control’s data-view and reloads from page one.',
    'handleSelectRow': 'Selects the row’s data-id unless the click originated in a nested link, button or form control.',
    'handleRowKeyDown': 'Selects a focused row on Enter or Space; ignores bubbled key events from controls inside the row.',
    'selectRecord': 'Stores the selected row ID and updates row highlighting for the detail sidebar; ignored while the panel is locked.',
    'handlePrevious': 'Subtracts 25 from the offset, clamped at zero, and loads the earlier page without preserving row selection.',
    'handleNext': 'Adds 25 to the offset and loads the next page without preserving row selection.',
    'handleRefresh': 'Reloads the current scope and preserves selection when the panel is unlocked.',
    'handleConvertLead': 'Opens a blank tab synchronously, generates the native conversion URL and navigates that tab. A blocked pop-up produces an actionable warning. A 750 ms monitor detects tab closure and schedules refresh; a navigation error closes the blank tab.',
    'handleLeadDecision': 'Accepts INTEREST_NOT_PROGRESSED or APPLICATION_REJECTED from the clicked row, confirms the rejection, calls updateLeadDecision and reloads without preserving selection. Rejection retains the Lead.',
    'handleOpenReminders': 'Starts a communication draft using the current HEAVY_DUE, STAFF_DUE or LOGO_DUE view as the email kind.',
    'handleOpenInvitations': 'Starts an INVITATION draft for the clicked Lead ID, passed from the row’s data-id.',
    'handleOpenFinalPack': 'Starts a FINAL_PACK draft for the currently filtered completed/unsent scope.',
    'openCommunication': 'Uses one supplied record ID or calls getCommunicationRecordIds for the full current filter scope. Rejects empty or more-than-500 selections before buildDraft. Stores the original IDs, initially selects eligible recipients, opens the modal and invalidates competing dashboard requests.',
    'applyCommunicationDraft': 'Stores the server draft and marks it fresh. Selects eligible recipients using either the supplied previous selection IDs or selectEligible. Sets subject/body and recipient labels, chooses the first selected preview recipient and immediately schedules preview.',
    'handleRefreshCommunication': 'Rebuilds the draft for the original record ID set. Retains edited subject/body and previously selected IDs only when still eligible. Clears preview readiness until the rebuilt draft is previewed; ignores superseded responses.',
    'handleCommunicationSubjectChange': 'Stores the input subject and schedules a 300 ms preview refresh; ignored while preparing or queuing.',
    'handleCommunicationMessageChange': 'Stores the edited message body and schedules a 300 ms preview refresh; ignored while preparing or queuing.',
    'handleRecipientSelection': 'Updates only the clicked recipient’s selection, allowing selection only if eligible, then refreshes preview immediately.',
    'handleSelectEligibleRecipients': 'Selects every eligible draft recipient and refreshes preview immediately.',
    'handleClearRecipients': 'Clears all recipient selections and invalidates the preview immediately.',
    'handlePreviewRecipientChange': 'Stores the selected preview record ID and immediately requests its merged preview.',
    'communicationRequest': 'Builds kind, runId, subject, messageBody and the selected recipient recordId/fingerprint pairs. The same request contract is used for preview and queuing.',
    'invalidateCommunicationPreview': 'Cancels the timer, increments previewSequence and communicationVersion, clears the HTML and resets preview-ready/loading flags so obsolete content cannot enable Send.',
    'queueCommunicationPreview': 'Invalidates the previous preview, requires a fresh draft, ensures the preview ID is still selected and requires nonblank subject/body. Schedules renderCommunicationPreview after 300 ms by default, or immediately for selection/draft changes.',
    'renderCommunicationPreview': 'Calls previewMessageJson with the current request and preview record ID. Accepts only the current sequence while the modal is open; swaps the hosted logo for the local static resource and adapts the preview width. A nonempty result enables preview readiness.',
    'handleCloseCommunication': 'Closes an idle dialog, invalidates preview/communication responses and clears the draft and recipients. Restores the launching control’s focus unless deferred for the post-send refresh.',
    'handleSendCommunication': 'Snapshots the reviewed request, version and communication sequence, asks for send confirmation, then rechecks those values and preview readiness before queueMessagesJson. Zero queued rows force a recipient refresh; successful queuing closes the modal and reloads the panel. Skipped recipients produce a warning result.',
    'showEmailToast': 'Displays the supplied queue result; errors remain sticky, while other toasts are dismissible.',
    'handleModalFocus': 'Remembers the currently focused dialog control for keyboard-boundary checks.',
    'handleModalKeyDown': 'Escape attempts to close the dialog; Tab/Shift+Tab wrap between its first and last enabled visible controls.',
    'modalFocusableControls': 'Returns enabled visible buttons, Lightning inputs/textareas/comboboxes, links and tabindex=0 elements inside the dialog.',
    'handleModalFocusOut': 'Returns escaped focus to the first or last control according to the Tab direction, unless the dialog is closed/busy or focus remains inside.',
    'restoreModalFocus': 'On the next timer turn, returns focus to the connected launch control; if unavailable, uses the header refresh button.',
    'resetAndLoad': 'Sets offsetRows to zero and calls loadDashboard with preserveSelection false.',
    'handleMilestone': 'Accepts only the five known base/top-up quote, invoice and payment actions, confirms the clicked booking/action, calls updateMilestone and reloads with that booking selected. Displays an Update not saved error on failure.',
    'readError': 'Uses error.body.message, then error.message, then the Master Panel loading fallback.'
}
RELATED = {
    'wiredRelationships': 'Reactively calls getRelationships for recordId/objectApiName. On success adopts the server title/mode/empty text and normalises its account, contacts and opportunities; on failure shows the relationships loading error.',
    'showsOpportunities': 'Shows the booking-history view when the server mode is opportunities.',
    'showsRelationships': 'Shows the account/contact view when the server mode is relationships.',
    'objectApiNameIsContact': 'True on Contact records, allowing Contact-specific presentation.',
    'hasOpportunities': 'True when the returned booking-history list has at least one Opportunity.',
    'hasContacts': 'True when the returned linked-contact list is nonempty.',
    'hasOpportunityRelationships': 'True when the booking has an Account or at least one linked Contact to display.',
    'normalizeOpportunity': 'Adds the Lightning record URL, GBP amount with up to two decimals, and en-GB close date parsed at local noon. Missing amount/date displays an em dash; the contact label distinguishes Primary contact from Linked contact.',
    'normalizeAccount': 'Adds the Account’s /lightning/r/Account/<id>/view record link.',
    'normalizeContact': 'Adds the Contact record link, primary/role/linked-contact label, phone/email fallbacks and a mailto link only when an address exists.'
}
RETRY = {
    'invoke': 'Headless action guarded against simultaneous invocation. A 006 ID calls retryApprovalEmail; 00Q calls retryAcknowledgement and adapts its result; other IDs call retryDispatch. Notifies Lightning that the source record changed. A refresh failure retains the action result and asks for a page refresh; finally clears the running guard.'
}
LWC_NOTES = {'nteManagementHome': HOME, 'nteMasterPanel': PANEL, 'nteRelatedOpportunities': RELATED, 'nteRetryEmail': RETRY}
