from pathlib import Path
from xml.sax.saxutils import escape
import textwrap
R=Path(__file__).resolve().parents[2]/'documentation/diagrams';R.mkdir(exist_ok=True)
def start(w,h):return [f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}"><defs><marker id="a" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="#385365"/></marker></defs><rect width="100%" height="100%" fill="white"/>']
def text(s,x,y,t,size=16,anchor='start',color='#172D3E'):
    s.append(f'<text x="{x}" y="{y}" text-anchor="{anchor}" font-family="Arial,sans-serif" font-size="{size}" fill="{color}">{escape(t)}</text>')
def box(s,x,y,w,h,name,lines,fs=14):
    s.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="5" fill="#F6F8FA" stroke="#91A8B5"/><path d="M{x+5} {y} H{x+w-5} Q{x+w} {y} {x+w} {y+5} V{y+33} H{x} V{y+5} Q{x} {y} {x+5} {y}" fill="#1C3B50"/>')
    text(s,x+12,y+23,name,20 if fs==18 else 16,color='white')
    for i,l in enumerate(lines):text(s,x+12,y+56+i*21,l,fs)
def line(s,x1,y1,x2,y2,label='',lx=None,ly=None,dash=False):
    s.append(f'<path d="M{x1} {y1} L{x2} {y2}" fill="none" stroke="#385365" stroke-width="2" marker-end="url(#a)"'+(' stroke-dasharray="6 4"'if dash else '')+'/>')
    if label:text(s,lx if lx is not None else (x1+x2)/2,ly if ly is not None else (y1+y2)/2-8,label,13,'middle')
def save(s,n):s.append('</svg>');(R/(n+'.svg')).write_text(''.join(s))
s=start(960,555)
box(s,20,35,270,125,'Public static pages',['Ten Web-to-Lead forms','Shared config and form engine','Org-specific field IDs'])
box(s,345,35,270,125,'Salesforce intake',['Lead submissions','Four after-save Flows','Native conversion'])
box(s,670,35,270,125,'Relationship and booking',['Account and Contact reused','One event Opportunity','One Primary Contact Role'])
line(s,290,96,345,96,'POST',318,81)
line(s,615,96,670,96,'Convert',642,81)
box(s,20,315,270,140,'NTE Management app',['Master Panel and Home','Native records and reports','Relationship and retry LWCs','Operates through Apex APIs'])
box(s,345,315,270,140,'Apex services and audit',['Pricing and supplementary data','Approval and email dispatch','Payment request snapshots','After-commit queue workers'])
box(s,670,315,270,140,'External delivery',['Salesforce outbound email','Stripe fixed Payment Links','Manual payment confirmation','External logo and pack URLs'])
line(s,290,375,345,375,'Apex',318,360)
line(s,615,375,670,375,'API',643,359)
line(s,480,160,480,315,'Flow invokes service',565,240)
line(s,805,160,550,315,'Saved booking facts',774,236)
text(s,20,505,'Outside the integration: general attendee ticketing, quote/invoice creation, refunds and binary logo storage.',16)
text(s,20,535,'Custom metadata holds destinations and merchant selection; protected external credentials hold the API key.',15)
save(s,'system')
s=start(980,650)
box(s,345,20,270,100,'Submission  Lead',['Application, EOI, guest or update','Conversion IDs are native outputs'])
box(s,20,225,250,115,'Organisation  Account',['Latest NTE classification','Standard organisation identity'])
box(s,345,225,270,115,'Event booking  Opportunity',['Record type NTE_Event_Opportunity','Initial price and separate top-up','Finance and preparation history'])
box(s,690,225,250,115,'NTE_Payment_Request__c',['Booking snapshot and Stripe IDs','Opportunity__c lookup','Charge_Key__c unique external ID'])
box(s,20,445,250,105,'Person  Contact',['Latest NTE classification','Primary recipient email'])
box(s,345,445,270,105,'OpportunityContactRole',['OpportunityId and ContactId','IsPrimary and Role','Exactly one Primary required'])
box(s,690,445,250,105,'NTE_Email_Dispatch__c',['Lead__c or Opportunity__c','Recipient and content snapshot','Dispatch_Key__c unique ID'])
line(s,480,120,480,225,'Convert / copy',555,182,True)
line(s,270,280,345,280,'0..1 : 0..*',307,264)
line(s,615,280,690,280,'0..1 : 0..*',652,264)
line(s,270,492,345,492,'1 : 0..*',306,476)
line(s,480,445,480,340,'0..* : 1',540,398)
line(s,615,326,745,445,'0..1 : 0..*',726,385)
s.append('<path d="M615 70 H960 V424 H817 V445" fill="none" stroke="#385365" stroke-width="2" marker-end="url(#a)"/>')
text(s,765,62,'Lead lookup  0..1 : 0..*',14,'middle')
line(s,145,340,145,445,'0..1 : 0..*',215,398)
s.append('<path d="M145 550 V588 H817 V550" fill="none" stroke="#385365" stroke-width="2" marker-end="url(#a)"/>')
text(s,480,578,'Dispatch Contact__c lookup  0..1 : 0..*',14,'middle')
text(s,20,620,'Lookup deletion is SetNull for custom audit relationships. Dotted line denotes conversion, not a lookup.',15)
text(s,20,644,'Default routing and Stripe configuration are custom metadata records; runtime resolves them by name.',15)
save(s,'data')
s=start(960,825)
steps=[('Review application',['Operator chooses Account and Contact, then creates a new event Opportunity.']),('Native conversion supplies related identities',['Salesforce supplies ConvertedAccountId, ConvertedContactId and ConvertedOpportunityId.']),('Reprice and copy in the conversion transaction',['NTEPricingService returns current pricedLead; Flow assigns exact booking fields and Amount.']),('Save pending approval and participant classification',['Flow queues explicit Lead and Opportunity IDs; Account/Contact get latest NTE summaries.']),('After commit prepare the optional Stripe request',['For selected paid Stripe bookings, create/reuse and verify the saved fixed charge/link.']),('Render to the exact Primary Contact and send',['Validate saved price and preparation links; choose exhibitor, partner or complimentary copy.']),('Persist the individual email outcome',['Opportunity approval audit plus Task; accepted Stripe email stamps quote/invoice, never payment.'])]
for i,(name,lines) in enumerate(steps):
    y=20+i*110;box(s,45,y,870,92,str(i+1)+'  '+name,[t for l in lines for t in textwrap.wrap(l,90)],fs=18)
    if i<6:line(s,480,y+92,480,y+110)
text(s,45,810,'First manually recorded base payment later queues one distinct booking-confirmation dispatch.',16)
save(s,'conversion')
s=start(960,825)
steps=[('Create supplementary Lead',['Staff, heavy-vehicle or logo form posts its target booking reference.']),('Reset submitted success fields and queue exact IDs',['Creation Flow invokes applyUpdates; NTEUpdateSubmissionJob runs after commit.']),('Reload in creation and ID order and match reference',['Require one eligible NTE booking; source event code does not retarget the reference.']),('Validate and merge accepted fields per booking',['Check audience, declarations, roster counts, immutable top-up and complete vehicle groups.']),('Save booking changes and applied identity together',['Savepoint protects the Opportunity update plus the Lead applied-booking audit.']),('Attempt staff or heavy-vehicle receipt separately',['Use the matched booking Primary Contact; receipt failure preserves already saved data.']),('Keep or delete the source submission as appropriate',['Delete eligible temporary staff/vehicle Leads only after accepted receipt; retain logo/error records.'])]
for i,(name,lines) in enumerate(steps):
    y=20+i*110;box(s,45,y,870,92,str(i+1)+'  '+name,[t for l in lines for t in textwrap.wrap(l,90)],fs=18)
    if i<6:line(s,480,y+92,480,y+110)
text(s,45,810,'Invalid or ambiguous requests remain auditable Leads. A receipt retry never reapplies booking changes.',16)
save(s,'updates')
print('Created four diagram SVG sources')
