"""Curated method explanations for the frozen implementation reference."""
NOTES={}
def group(cls,names,note):
    for name in names.split(): NOTES[(cls,name)]=note

C='NTEBookingContactService'
group(C,'primaryContacts','Loads roles and Contacts for the supplied booking IDs in the requested USER_MODE or SYSTEM_MODE. The overload optionally locks them. Returns a Contact only for a booking with exactly one Primary role; it never chooses an event-day contact or arbitrary role as fallback.')
group(C,'singlePrimaryContactIds','Indexes Primary roles by Opportunity. A second Primary role makes that booking ambiguous and removes it from the usable result.')

C='NTEPricingService'
group(C,'status','Returns Review required when any selection/count/eligibility check failed; otherwise Calculated. This is the pricing-result status, not a payment state.')
group(C,'priceApplicationsForConversion','Validates requested Lead IDs and supported application types, reloads current inputs, calculates each application and returns pricedLead responses in request order. It does not persist Lead prices or reprice another booking.')
group(C,'recalculateLeads','Maintenance entry point: reloads and reprices matching application Leads, then performs partial SYSTEM_MODE updates. SaveResult outcomes are not exposed; see the issues register before a historical migration.')
group(C,'loadLeadsForPricing','Queries the source choices, staff allocation and component fields required for current Lead pricing; non-application or missing requested records cannot become valid conversion results.')
group(C,'recalculateOpportunities','Maintenance entry point for stored booking prices. Recalculates the initial components while preserving separately accepted staff top-up facts; partial DML outcomes are not returned.')
group(C,'applyLeadPricing','Writes the calculated component, included/extra/total staff, listed total, status and catalogue version onto an in-memory application Lead, overriding browser-supplied derived prices.')
group(C,'applyOpportunityPricing','Maps booking fields into the pricing calculator and writes current initial pricing components. Keeps the booking allocation/top-up separation described in the finance chapter.')
group(C,'componentTotal','Adds sponsor, exhibition space, power and additional initial staff amounts, treating null components as zero. VAT and later staff top-ups are outside this base total.')
group(C,'calculate','Authoritative allowlist algorithm. Distinguishes partner package sums from one exhibitor space, checks active category/restricted-space eligibility and whole counts, derives included and chargeable staff, and returns Review required for invalid input.')
group(C,'includedStaffForSpace','Returns four included places for the explicit double-space allowlist and two for other recognised exhibitor spaces.')
group(C,'isApplication','Recognises only Partner / Sponsor Application and Exhibitor Application.')
group(C,'qualifiesForPowerDiscount','Matches the five explicit qualifying organisation category labels; approximate or altered text cannot receive the discount.')
group(C,'isKnownExhibitorCategory','Caches active schema picklist values and requires an exact recognised category. This makes the field definition part of the pricing contract.')
group(C,'isEligibleForRestrictedSpace','Checks the category-to-space restrictions for charity, local government, blue-light and trade-association choices.')
group(C,'decimalFromText','Parses a stored numeric text count; blank/unparseable input returns null for the caller to classify rather than inventing a valid allocation.')
group(C,'valueOrZero','Normalises a nullable amount to zero for arithmetic after eligibility checks.')

C='NTEInboundLeadService'
group(C,'send','Default delivery adapter delegates the complete message list to Messaging.sendEmail; a replaceable adapter supports deterministic partial-result tests.')
group(C,'EmailDispatch','Associates one message with its Lead ID and applicant-versus-internal audit side so results cannot be assigned to a different recipient.')
group(C,'routeAndAcknowledge','Flow entry point for five NTE routes. Reloads Leads, resets forged creation decisions/statuses, recalculates application pricing, resolves the configured owner and templates, sends only required unaccepted receipt/notification sides and records per-side outcomes. Application applicant receipts remain suppressed.')
group(C,'dispatchAndRecord','Coordinates delivery and durable audit updates around a savepoint so an audit persistence failure does not leave a falsely accepted intake state.')
group(C,'sendDispatches','Submits the accumulated list within the shared email invocation budget and maps every returned result, missing result or exception back to its own audit side.')
group(C,'writeAudits','Persists applicant/internal status, timestamp and combined errors for each Lead. Successful sides remain accepted during a later failed-side retry.')
group(C,'isUsableEmail','Checks the address shape required before attempting a message; a missing or malformed address becomes a visible delivery failure.')
group(C,'setDispatchStatus','Sets the applicant or internal notification status selected by the dispatch flag.')
group(C,'fail','Marks only the affected side Failed and appends the specific error to that Lead audit.')

C='VolunteerInboundLeadService'
group(C,'send','Default send adapter calls Messaging.sendEmail for the complete list; tests substitute controlled per-message results.')
group(C,'Dispatch','Keeps the Lead, applicant/internal side and message together for exact result mapping.')
group(C,'notifyOwner','Flow entry point restricted to the matching volunteer form type and LeadSource. Resets forged new-record acceptance, resolves applicant and current active owner independently, sends the two volunteer templates and preserves already accepted sides on retry.')
group(C,'dispatchAndRecord','Wraps message and audit processing so persistence problems leave a recoverable outcome rather than pretending the stored audit is complete.')
group(C,'sendDispatches','Sends the accumulated volunteer messages using the remaining shared invocation budget; records partial failures and missing results individually.')
group(C,'writeAudits','Saves the volunteer applicant/internal acceptance fields and errors on the source Lead.')
group(C,'isUsableEmail','Rejects missing or malformed applicant/owner addresses before delivery.')
group(C,'setStatus','Writes the correct volunteer applicant or internal status field.')
group(C,'fail','Accumulates an error and marks just the affected volunteer delivery side Failed.')

C='NTEExhibitorApprovalEmailService'
group(C,'sendApprovalConfirmation','Invocable conversion entry point. Validates explicit Lead/Opportunity associations, coalesces requests into a saved pending batch and schedules processing after the conversion transaction commits.')
group(C,'retryApprovalEmail','User action for one failed booking. Requires an eligible unsent, non-pending booking and its exact converted source application; returns the queue outcome instead of claiming an email was delivered.')
group(C,'saveRequests','Deduplicates and validates requests, checks prior approval/audit evidence, writes Pending and batch identity on eligible bookings and returns the saved booking IDs.')
group(C,'ApprovalQueueable','Stores the batch key and delivery/test-source flags for the asynchronous approval worker.')
group(C,'execute','Queueable.execute attaches a finalizer and processes the saved batch; ApprovalFinalizer.execute marks only still-pending records in its batch failed after an unhandled worker error. The signature distinguishes the two implementations.')
group(C,'resumeAfterStripe','Resumes the same approval batch after payment-link work without generating a new conversion request.')
group(C,'finishStripeBooking','Resumes approval for the exact booking represented by a completed payment request, preserving the original batch identity.')
group(C,'ApprovalFinalizer','Captures the approval batch key used to isolate unexpected-failure recovery.')
group(C,'processRequests','Internal/test-facing bridge from explicit Request values into the same saved-request processing path.')
group(C,'processPendingBatch','Loads pending bookings for one batch, optionally one subset, validates source association, Primary Contact, saved price, template and preparation settings, coordinates Stripe readiness and sends in bounded pages. Persists individual accepted/failed outcomes and audit Tasks; chains remaining work.')
group(C,'renderBookingEmail','Renders the stored Contact/Opportunity template, supplies event/organisation/finance/payment/preparation markers, and builds a readable text alternative. The paymentConfirmation flag selects paid presentation without creating another payment request.')
group(C,'replaceTemplateMarkers','Replaces only source-owned HTML comment markers in one pass. Recipient text that resembles a merge token remains literal data.')
group(C,'plainTextFromHtml','Removes layout-only markup while preserving meaningful paragraphs, itemised amounts and usable links.')
group(C,'templateFor','Selects the exhibitor or partner provisional/complimentary stored template by saved participant type.')
group(C,'savedPriceError','Checks saved status, base amount and itemised component consistency before any booking/paid confirmation. Rejects unknown zero, invalid quantities and participant-incompatible components.')
group(C,'validLineItem','Validates a quantity, unit price and extended total as one internally consistent line. The String overload parses count text; the Decimal overload checks the numeric relationship.')
group(C,'paymentConfirmationError','Applies the paid-confirmation prerequisites to the saved booking and preparation routing; payment history is not changed by a rendering failure.')
group(C,'paymentNote','Chooses provisional, complimentary, manual-payment or Stripe wording from saved booking/request facts.')
group(C,'financeSummary','Builds the participant-specific net component table plus aggregate VAT and gross amounts for every payment method; Stripe uses the verified saved request. Paid presentation omits a new Pay Now request.')
group(C,'stripePaymentButton','Builds the payment call-to-action only from the verified saved Stripe request URL.')
group(C,'componentTotal','Sums the saved initial sponsor/space/power/staff components for itemisation consistency checks.')
group(C,'preparationConfigurationError','Validates the booking reference and the relevant staff/logo/vehicle destinations before promising the recipient can complete preparation.')
group(C,'preparationLinks','Builds the audience-specific preparation buttons, with vehicle details included when applicable.')
group(C,'staffUrl','Selects the partner or exhibitor staff form from routing metadata.')
group(C,'needsVehicleLink','Determines whether the saved heavy-vehicle answer requires exposing the vehicle-details route.')
group(C,'shortEventLabel','Derives the recipient-facing short event label from the saved edition code.')
group(C,'validUrl','Accepts usable HTTPS preparation destinations; invalid settings fail the affected booking email.')
group(C,'validBookingReference','Checks the supported NTE reference grammar before emitting preparation instructions.')
group(C,'button','Builds one escaped, consistently sized HTML preparation button for the current column count.')
group(C,'quantityLabel','Formats a component quantity and unit amount for the saved itemisation. Overloads accept stored text or numeric quantities.')
group(C,'moneyRow','Builds one escaped label/GBP amount row in the booking finance table.')
group(C,'amount','Resolves the booking base amount used by the renderer according to the saved pricing rules.')
group(C,'valueOrZero','Normalises a missing numeric component for validated arithmetic/presentation.')
group(C,'money','Formats a Decimal as GBP with two decimal places.')
group(C,'escape','Escapes dynamic text for insertion into HTML.')
group(C,'requestMap','Produces the explicit Opportunity-to-Lead request association and rejects conflicting mappings.')
group(C,'failedUpdate','Builds a sparse Opportunity update setting failed approval status and bounded error text.')
group(C,'failPendingBatch','Marks still-pending members of the identified batch failed; does not demote accepted messages or another batch.')
group(C,'auditFor','Constructs the completed Task audit containing booking, recipient, template, status and error/outcome evidence.')
group(C,'isEligibleComplimentaryBooking','Requires the supported zero-price charity exhibition choice and known saved zero-charge pricing; a missing amount alone is not complimentary.')
group(C,'truncate','Bounds audit/error text to its persistence limit.')

C='NTEEmailDispatchService'
group(C,'buildDraft','Builds a kind-specific editable subject/body and recipient eligibility snapshot for exactly the requested IDs. Does not render every recipient HTML or send messages.')
group(C,'previewMessageJson','Strict JSON boundary that deserialises and validates a browser draft then returns one selected recipient preview.')
group(C,'queueMessagesJson','Strict JSON boundary that validates a browser draft and serialises the queued/skipped response.')
group(C,'previewMessage','Revalidates the selected recipient/fingerprint, personalises subject/body and returns that recipient HTML without creating dispatches.')
group(C,'queueMessages','Locks/reloads the exact selection, checks fingerprints and aggregate payload limits, persists unique dispatch rows, queues the saved IDs and returns accepted queue counts.')
group(C,'dispatchForRequest','Creates a dispatch snapshot with the kind/run/record key, original recipient, reviewed content, personalised content and fingerprint.')
group(C,'validateQueueSize','Checks combined raw, personalised and escaped HTML size before retaining a full bulk payload. Individually legal messages can still exceed the aggregate budget.')
group(C,'queueBookingConfirmation','Creates or reuses the unique first-base-payment confirmation dispatch. This automatic message has fixed project rendering and cannot be sent through the editable mass composer.')
group(C,'retryDispatch','Convenience entry point for the record action; delegates one failed dispatch ID to the same retry mechanism.')
group(C,'recentDispatches','Returns up to 1000 recent dispatch history DTOs for the selected source records, including outcome, recipient and retry information.')
group(C,'retryFailed','Reuses only Failed dispatches with their existing identities. Rechecks current eligibility/recipient/fingerprint; paid-confirmation recovery deliberately rebuilds its current valid primary-recipient presentation.')
group(C,'enqueue','Schedules a worker only for the saved dispatch ID list; queue failure is converted into a truthful persisted failure outcome.')
group(C,'DispatchQueueable','Stores saved dispatch IDs and the controlled delivery-bypass flag for a worker page.')
group(C,'execute','The Queueable overload attaches its finalizer and processes a page; the Finalizer overload marks still-queued rows failed after an unexpected worker exception. Their parameter types distinguish the paths.')
group(C,'DispatchFinalizer','Captures the exact dispatch IDs whose pending state must be recovered after worker failure.')
group(C,'processQueued','Locks queued rows, reloads recipients and verifies unchanged reviewed facts, renders validated messages, sends bounded groups, maps individual outcomes, synchronises source status and chains remaining saved IDs.')
group(C,'failQueued','Marks only still-Queued target dispatches Failed with a bounded reason and updates related source status where applicable.')
group(C,'loadRecipients','Kind-specific query and eligibility engine for invitations, staff/vehicle/logo reminders, final packs and paid confirmations. Uses one Primary Contact for booking mail, validates route links/references and explains every exclusion.')
group(C,'updateSourceStatuses','Synchronises invitation progression and final-pack state from dispatch outcomes. Sent history is preserved; reminder sends do not mark preparation complete.')
group(C,'recipientMap','Indexes recipient DTOs by target record ID for exact selection and outcome lookup.')
group(C,'sameRecipient','Compares the saved recipient association/address/fingerprint with the freshly loaded recipient to stop an old reviewed email reaching changed details.')
group(C,'targetId','Returns the Lead or Opportunity target from a dispatch row.')
group(C,'normalizeKind','Restricts the requested communication type to the implemented allowlist.')
group(C,'validateIds','Enforces permitted object IDs, nonempty bounded selections and duplicate handling for the selected kind.')
group(C,'parseRequestJson','Rejects malformed, unknown-field or oversized JSON before strict DraftRequest deserialisation.')
group(C,'validateRequest','Validates run identity, subject/body lengths, token/content rules, selected IDs and required fingerprints for the reviewed draft.')
group(C,'fingerprint','Hashes kind plus recipient/booking/route facts that must remain unchanged between review and delivery.')
group(C,'dispatchKey','Builds the stable SHA256 key from kind, run and target. Payment confirmation uses its fixed booking-payment run identity.')
group(C,'hash','Returns the SHA256 digest used for snapshot and idempotency identities.')
group(C,'route','Resolves application, staff, vehicle, logo or final-pack URL by kind and participant type from the Default routing metadata.')
group(C,'configuredRouting','Returns the current Default routing record or the injected test configuration.')
group(C,'validLink','Validates configured HTTPS destinations before preview/queue/delivery.')
group(C,'titleFor subjectFor bodyFor','Returns the kind-specific default composer title, subject or plain-text message. Personalisation occurs later against the selected recipient.')
group(C,'personalise','Replaces the supported greeting, organisation, booking reference, event and route tokens in one pass; token-looking recipient values remain literal.')
group(C,'normaliseLines','Normalises CRLF/CR to LF for consistent editor and text-alternative handling.')
group(C,'personalisedContentIssue','Rechecks expanded subject/body sizes and content after token expansion, including long recipient values.')
group(C,'htmlFor','Builds the escaped branded HTML from the personalised plain-text composer content, including the appropriate route action.')
group(C,'escape','Escapes dynamic values for HTML output.')
group(C,'emailError','Extracts a useful delivery error from a failed Salesforce send result.')
group(C,'resultFor','Constructs the queue response with queued/skipped counts and operator-facing outcome text.')
group(C,'handled','Creates the AuraHandledException used for a controlled LWC-visible validation error.')

C='NTEStripeClient'
group(C,'NTEStripeClient','Selects an allowed test/live named credential; all subsequent API calls use that protected endpoint identity.')
group(C,'verifyAccount','Reads account and balance, checks the expected merchant and mode, and requires charges_enabled for live operation before permitting resource creation.')
group(C,'createPrice','Creates the one-time GBP Price with a year-neutral Product name, saved gross minor units, metadata and stable Price idempotency key.')
group(C,'createLink','Creates a fixed quantity-one card Payment Link for the verified Price. Disables promotion codes, adjustable quantities, automatic tax and invoice creation; limits completed sessions to one.')
group(C,'verifyLink','Retrieves the link and expanded Price and validates amount, currency, merchant mode, metadata, enabled options, quantity/session limits and payment URL before use in email.')
group(C,'toMinorUnits','Converts GBP to exact pence using the explicit range and decimal-precision contract; rejects unsupported sub-penny or out-of-range charges.')
group(C,'validPaymentUrl','Checks the buy.stripe.com URL shape and test/live path rules, excluding unexpected query/fragment/host variants.')
group(C,'validateCharge','Validates the saved charge identity, reference, amount and metadata needed for Price/Link requests.')
group(C,'requireVerifiedAccount','Requires a prior matching merchant/mode verification for the charge before any write or link acceptance.')
group(C,'verifyPrice','Validates the Price ID, active state, unit amount, currency, one-time billing and metadata against the charge snapshot.')
group(C,'requireId','Checks the expected Stripe resource prefix and supported identifier shape.')
group(C,'objectValue','Requires an object-shaped nested API response property rather than silently accepting an unexpected type.')
group(C,'longValue','Parses an API integer amount without accepting incompatible values.')
group(C,'request','Central form-encoded HTTP transport with 20-second timeout, pinned Stripe API version, protected credential, stable idempotency header and bounded error handling. Parses object JSON responses.')

C='NTEStripeBookingService'
group(C,'configuration','Loads Default Stripe custom metadata or injected test configuration.')
group(C,'selected','Applies Enabled and optional reference-prefix/recipient scope to a prospective booking.')
group(C,'configurationError','Checks required merchant/org/environment/tax configuration and the current Salesforce org binding.')
group(C,'bookings requests','Executes the fixed field-set SYSTEM_MODE query with supplied bind variables and optional row lock for booking or payment-request records.')
group(C,'prepareProvisionalBatch','Inspects one approval batch, validates source bookings/contacts, creates or reuses their unique Booking payment requests, and schedules payment work. Returns whether approval must wait for that route.')
group(C,'convertedApplications','Bulk-loads converted source Leads per booking so association checks do not query once per record.')
group(C,'eligibilityError','Rejects unsupported, unconverted/mismatched, paid/cancelled, wrong-org, invalid-price or unusable-recipient bookings before making a link.')
group(C,'fingerprint','Hashes the booking identity, price components, recipient, event and payment configuration to bind external resources to the exact saved proposal.')
group(C,'PaymentWork','Stores request IDs and approval continuation context for callout-capable queue processing.')
group(C,'execute','PaymentWork.execute processes saved requests and continues the same approval workflow; PaymentFinalizer.execute records unhandled failures and resumes failure-aware approval handling.')
group(C,'PaymentFinalizer','Captures request IDs and batch identity for bounded failure recovery.')
group(C,'processPayment','Locks/rechecks saved state before callouts, verifies account, creates/reuses Price and Link with stable keys, verifies the resulting contract and rechecks facts afterward. Ambiguous attempts older than 23 hours require review.')
group(C,'charge','Builds the API client Charge contract solely from the saved payment-request snapshot.')
group(C,'emailFailure','Creates a sparse failed approval update for the booking affected by a payment preparation failure.')
group(C,'preloadEmailRequests','Bulk-loads payment requests into a transaction cache for approval rendering.')
group(C,'paymentForEmail','Returns the cached saved Booking request used in the email finance table/payment button.')
group(C,'emailReadinessError','Verifies the current booking/recipient against the saved verified request, environment and recent verification before permitting email delivery.')
group(C,'recordEmailAccepted','Updates the payment request email audit and appropriate booking quote/invoice milestones after Salesforce accepts the provisional message. It never marks payment received.')

C='NTEUpdateSubmissionJob'
group(C,'NTEUpdateSubmissionJob','Stores the serialized Lead ID payload and controlled email-bypass flag for after-commit processing.')
group(C,'execute','Deserialises the exact queued IDs, invokes processLeadIds and records an unexpected worker failure against those source Leads.')
C='NTEUpdateSubmissionService'
group(C,'OrderedSubmission','Wraps a source Lead for stable chronological processing when several submissions target one booking.')
group(C,'compareTo','Orders by CreatedDate and then ID so a batch has deterministic first-valid top-up ownership.')
group(C,'applyUpdates','Invocable creation entry point. Resets submitted success/booking-identity audit values and queues supported supplementary Lead IDs; actual booking mutation occurs after commit.')
group(C,'recordUnexpectedFailure','Attempts to persist a bounded unexpected-worker error for the affected submission IDs while preserving accepted/applied evidence.')
group(C,'processLeadIds','Reloads and orders submissions, matches exact normalised references, rejects missing/ambiguous/invalid targets, validates each update and merges valid changes per booking. Saves booking plus applied audit atomically, sends receipts separately and deletes eligible successful temporary Leads.')
group(C,'buildOpportunityMatchIndex','Indexes eligible NTE booking references and marks duplicates ambiguous. Event code is not a second matching key; a unique reference is authoritative.')
group(C,'applyPartnerStaffFields','Replaces the free partner staff count/names and completion metadata from the accepted roster; does not create exhibitor staff charges.')
group(C,'applyExhibitorStaffFields','Applies initial names and the first valid immutable top-up purchase, calculates its separate amount and resets only its own invoice/payment milestones. Later name corrections preserve accepted quantities/finance.')
group(C,'initialStaffCount','Resolves the booking initial allocation from saved initial fields with the supported legacy fallback; invalid counts remain invalid.')
group(C,'combineNames','Joins initial and top-up roster lines into the final staff list while enforcing the stored long-text boundary.')
group(C,'decimalFromText integerFromText','Parses whole staff counts without turning malformed, fractional or missing values into a valid roster allocation.')
group(C,'validationErrorFor','Enforces form-to-booking audience, reference, declaration, roster count/name consistency, immutable top-up and complete heavy-item/contact requirements. Logo confirmation has its distinct lighter declaration rule.')
group(C,'incompleteOptionalItem','Detects partially completed optional heavy-item groups so a replacement cannot silently clear a previously complete set.')
group(C,'nonBlankLineCount','Counts nonempty roster lines; the count must match the declared allocation.')
group(C,'applyHeavyFields','Replaces the heavy item/haulier/delivery/contact fields from a complete valid submission and marks heavy details provided; stale optional fields are explicitly cleared.')
group(C,'applyLogoFields','Idempotently sets logo-provided state/time while retaining previous completion evidence on repeat declarations.')
group(C,'isValidBookingReference','Checks the normalised NTE reference grammar used for the exact booking match.')
group(C,'acknowledgementTemplate','Selects the exhibitor staff, partner staff or heavy-vehicle receipt developer name. Logo updates do not request an acknowledgement email.')
group(C,'appliedBookingId','Reads the durable booking identity captured when the submission was applied; a current reference alone cannot manufacture that identity.')
group(C,'matchesAppliedBooking','Requires the saved applied identity/reference to agree with the booking before any receipt retry.')
group(C,'acknowledgementAudit','Builds the source Lead receipt acceptance/failure/timestamp update.')
group(C,'acknowledgementMessage','Builds the stored Lead-template receipt addressed to the matched booking Primary Contact, while using the preserved submission as merge context.')
group(C,'sendAcknowledgements','Loads templates and exact Primary Contacts in bulk, sends bounded receipt groups and maps outcomes per Lead. More than 100 receipts returns failure/retry guidance without undoing applied booking data.')
group(C,'retryAcknowledgement','User action retries only one failed receipt after verifying its applied booking and current Primary Contact. Does not replay booking field updates, rematch to another record or delete the source Lead.')
group(C,'templateIds','Maps the requested stored template developer names to Salesforce EmailTemplate IDs.')

C='NTERelatedOpportunityController'
group(C,'RelatedOpportunity','Projects the readable Opportunity into display fields, including event, reference, stage, amount and whether the current Contact role is Primary.')
group(C,'RelatedAccount','Projects the linked Account into its display name and record link.')
group(C,'RelatedContact','Projects a Contact Role into Contact details, role and Primary indicator.')
group(C,'getRelationships','Validates object/ID agreement and USER_MODE visibility. Account mode returns its NTE bookings; Contact mode follows its roles; Opportunity mode returns its Account and Contact roles. Caps list results at 200.')
group(C,'readableOpportunities readableRoles readableAccounts','Applies readable-field filtering to the selected object records before creating response DTOs. Each helper handles its named SObject type.')

C='NTE_MasterPanelController'
group(C,'FilterOption','Constructs one label/value filter option consumed by the LWC.')
group(C,'SummaryMetric EventOverviewRow PipelineStep WorkQueue HomeMetric HomePipelineRow HomeBookingMixSegment HomeBookingMix','Constructs the named response record for summary counters, breakdown/progress rows, operational queues or commercial charts. Values are assembled by the corresponding aggregate helpers; constructors do not mutate records.')
group(C,'compareTo compareRecordIds','Sorts combined Lead/Opportunity dashboard rows deterministically by modification time and record ID, keeping pagination stable across tied timestamps.')
group(C,'ReminderRecipient','Captures a booking, exact Primary Contact and resolved form URL for the retained legacy reminder draft API.')
group(C,'getHomeDashboard','Builds the selected edition commercial portfolio: pending/approved value, independently invoiced/paid/outstanding base and top-up amounts, pricing-review count, readiness and participant mix. Excludes closed losses and unrelated record types.')
group(C,'getDashboard','Normalises event/time/owner/view/pagination, executes USER_MODE counts and row queries, and returns consistent cards, refiners, report links, details and navigation limits.')
group(C,'getCommunicationRecordIds','Reloads the complete filtered target selection for a composer action, with strict stale-filter checks and a 501-record sentinel beyond the 500-recipient capacity. It does not use only the current page.')
group(C,'getUpdateEmailIssues','Returns up to 100 recent failed supplementary receipts associated by saved booking reference, including submissions whose event code differs from the booking edition.')
group(C,'updateLeadDecision','Locks and rechecks one active interest/application. Supports the permitted not-progressed/rejected decision, preserves accepted invitation/converted history and rejects stale or retired manual progression actions.')
group(C,'getReminderDraft','Retained legacy read-only reminder API: returns audience/subject/body and a bounded eligible recipient draft. Current LWC uses NTEEmailDispatchService instead.')
group(C,'sendUpdateReminders','Retired send entry point always raises a handled instruction to use the reviewed communication composer. It does not send messages.')
group(C,'updateMilestone','Locks an eligible booking in USER_MODE, validates quote/base/top-up invoice/payment order, stamps the exact flag/time/user and rejects repeated actions. First base payment queues one confirmation; top-up payment does not.')
group(C,'counts','Runs the scoped aggregate queries behind all operational counters using the shared finance/readiness clauses.')
group(C,'summary overview pipeline workQueues','Transforms scoped counts into top-level cards, event breakdowns, stage navigation or queue options respectively. These are views of the same bookings, not additive disjoint totals.')
group(C,'queue','Constructs one queue with its count, explanatory detail, related report and native-list URL.')
group(C,'selectedView','Resolves the current queue descriptor from the normalised view key and computed counts.')
group(C,'rows','Queries the required Lead/Opportunity fields for the chosen view, sorts/pages results, and for Recent merges both object types before slicing.')
group(C,'leadRow','Maps one Lead to panel columns/details, contact data, decision/invitation status and permitted review actions.')
group(C,'opportunityRow','Maps one booking and its exact Primary Contact to panel details, saved finance/readiness facts, missing-data reasons and next actions.')
group(C,'isComplete','Single in-memory completion rule: resolved quote, known/settled applicable base and top-up finance, staff and logo provided, and No heavy vehicles or Yes plus details provided. Pack sending is separate.')
group(C,'isUpdateRequired','Identifies missing staff/logo or unresolved required logistics; finance readiness is evaluated separately.')
group(C,'knownLeadValue','Returns the known application listed value; unknown/review-required pricing is excluded rather than treated as free.')
group(C,'knownOpportunityValue','Returns the known combined base and separate top-up commitment for commercial aggregation.')
group(C,'knownBaseOpportunityValue','Resolves the known saved base amount without including later top-up money.')
group(C,'addToMetric','Adds a qualifying record and known value to one Home metric.')
group(C,'addToPipeline','Adds count/value to the exhibitor or partner segment of a Home pipeline row.')
group(C,'addToBookingMix','Accumulates exhibitor/partner counts and values for the booking mix.')
group(C,'finalizeBookingMix','Calculates totals/segment proportions after accumulating the selected edition mix.')
group(C,'orderedMetrics orderedPipeline','Returns metrics or pipeline rows in the explicit display order rather than map iteration order.')
group(C,'isBaseBillable','Returns true for Invoice Required Yes, a positive listed base total or pricing requiring review. Keeping unknown pricing billable prevents an incomplete record bypassing finance.')
group(C,'leadPricingNeedsReview pricingNeedsReview','Identifies missing/invalid pricing for an application Lead or booking; used to expose review work and withhold misleading financial readiness.')
group(C,'hasKnownPricing','Implements the supported Calculated/non-null and known positive legacy pricing rule. Invalid/missing zero pricing is not accepted as complimentary.')
group(C,'isTopUpBillable','Returns true when Top Up Invoice Required is set or the separate staff top-up amount is positive.')
group(C,'isBillable','Returns whether either the base charge or the separate top-up requires finance.')
group(C,'baseInvoiceComplete topUpInvoiceComplete basePaymentComplete topUpPaymentComplete','Evaluates the named charge/milestone pair, treating a known non-billable charge as complete and requiring its own saved flag for a positive charge.')
group(C,'valueOrZero','Converts null to zero after known-price eligibility has been determined.')
group(C,'financeStatus','Presents the next unresolved quote/invoice/payment or pricing-review state from the mapped booking facts.')
group(C,'typeLabel typeIcon','Maps the supported form type to the participant label or icon used in panel rows.')
group(C,'leadStage','Presents recorded Converted, Rejected, Invited, Queued or current review state without reopening a decided Lead.')
group(C,'preferredContact','Combines the saved preferred contact method and timing for the detail panel.')
group(C,'leadViewClause','Adds the exact interest/application/guest/recent Lead filter for a normalised queue key.')
group(C,'activeInterestClause','Excludes converted, progressed and not-progressed interests from active review.')
group(C,'activeApplicationClause','Excludes converted and rejected applications from active review.')
group(C,'opportunityViewClause','Selects the quote/invoice/payment, preparation, completed or approved booking subset for the chosen view.')
group(C,'logisticsOutstandingClause','Expresses unresolved heavy-vehicle state in SOQL, including unknown answers rather than assuming No.')
group(C,'completeClause','SOQL counterpart of isComplete, used by counts and final-pack/completed selection. Must stay aligned with the in-memory rule.')
group(C,'billableClause baseBillableClause topUpBillableClause','Returns the SOQL predicate for any, base or separate top-up charge respectively.')
group(C,'pricingReadyClause pricingReviewClause','Returns the SOQL known-price or review-required predicate used consistently in finance queues.')
group(C,'anyInvoiceOutstandingClause','Selects bookings with an unresolved applicable base or top-up invoice.')
group(C,'allInvoicesProvidedClause','Requires both applicable invoices or known non-billable exceptions.')
group(C,'actionablePaymentClause','Selects a payment that can be recorded now, respecting quote, invoice and booking-first order while allowing independent top-up invoice work.')
group(C,'allPaymentsReceivedClause','Requires both applicable base and top-up payments, allowing known non-billable charges to pass.')
group(C,'quoteResolvedClause','Accepts no quote requirement or a saved provided quote.')
group(C,'notBillableClause baseNotBillableClause topUpNotBillableClause','Returns the complementary known non-billable predicates for combined, base or top-up finance. Unknown pricing is not equivalent to free.')
group(C,'viewCount','Returns the count associated with a normalised view key.')
group(C,'configurePagination','Clamps page size/offset to a valid accessible last page and the 2000-row browser cap, even when queues shrink between requests.')
group(C,'countLead countOpportunity','Executes the named object bound aggregate count in USER_MODE.')
group(C,'leadBaseWhere','Builds the supported NTE Lead/event/owner/creation-date base predicate.')
group(C,'opportunityBaseWhere','Builds the NTE record type, supported participant, nonblank event, open-or-won, owner and creation-date base predicate.')
group(C,'baseBinds','Produces bind variables for event, owner, time and required record type/form choices.')
group(C,'copyBindsWith','Copies a query bind map before adding a view-specific parameter.')
group(C,'eventOptions','Collects nonblank event codes from relevant main Leads/bookings and sorts them descending. Legacy codes remain selectable; unrelated/supplementary-only events do not become empty choices.')
group(C,'ownerOptions','Returns selectable owner label/ID options for the dashboard scope.')
group(C,'reportUrls','Resolves the stored NTE report IDs and builds native Lightning URLs, including the weekly finance report.')
group(C,'resolveEventCode','Preserves an explicit available edition; otherwise selects the highest available canonical NTE plus four-digit year, then falls back to the first option only if no canonical code exists.')
group(C,'communicationEventCode','Strictly validates a communication edition rather than silently substituting another when a draft action is stale.')
group(C,'normalizeTimeRange','Normalises dashboard time-range input to the supported choices.')
group(C,'communicationTimeRange','Rejects unsupported/stale communication time ranges instead of widening the intended recipient scope.')
group(C,'normalizeViewKey','Maps aliases and supported panel view keys to the canonical queue; falls back only for ordinary dashboard navigation.')
group(C,'normalizeOwnerId','Validates the selected owner ID or recognised all-owner choice before binding the query.')
group(C,'normalizeReminderView','Restricts the retained reminder API to the supported outstanding preparation views.')
group(C,'reminderBookings','Loads up to 2000 scoped candidate bookings for the retained legacy reminder draft, ordered by Account/name.')
group(C,'primaryContactsByOpportunity','Delegates exact Primary Contact resolution for the selected reminder bookings.')
group(C,'reminderTitle reminderSubject reminderBody','Supplies legacy kind-specific reminder presentation text; the active composer defaults are in NTEEmailDispatchService.')
group(C,'reminderUrl','Resolves the legacy reminder form destination from view, participant type and routing metadata.')
group(C,'personaliseReminder','Expands the retained legacy reminder body against one recipient snapshot.')
group(C,'reminderAuditTask','Builds the historical reminder audit Task shape. The retired send entry point cannot dispatch through this path.')
group(C,'closedTaskStatus','Finds a usable closed Task status for audit creation rather than assuming a target-specific label.')
group(C,'sinceAt','Converts the supported time-range choice into a CreatedDate lower-bound timestamp; all time has no lower bound.')
group(C,'safeMessage','Returns bounded useful exception text for the operator without replacing a specific controlled validation message.')
group(C,'handled','Creates an AuraHandledException for a controlled Lightning-visible error.')

group('NTEVat','rate','Uses the saved VAT rate where populated, otherwise the generated 20% policy rate.')
group('NTEVat','tax','Returns null for unknown net amounts, otherwise rounds net times rate to two decimal places using HALF_UP.')
group('NTEVat','gross','Adds the separately calculated aggregate VAT to the net charge, preserving null for unknown prices.')
group('NTEStripeClient','vatMessage','Formats the saved net subtotal, aggregate VAT and gross payable total for the checkout disclosure.')
